# General settings required by the application

terms_file_path : "./config/terms_to_follow.yaml"
elastic_index_name : "ml_conferences" 

logging_level : INFO

reconnect_stream :
    hours_to_reset_counter : "2"
    max_reconnects : "20"