# General settings required by the application

terms_file_path : "tweetlastic/config/terms_to_follow.yaml"

elastic_index_name : "ml_conferences" 
overwrite_index : False

logging_level : INFO

reconnect_stream :
    hours_to_reset_counter : "2"
    max_reconnects : "20"