name: run_tests

on:
    push:
        branches:
            - 'master'
        paths-ignore:
            - 'README.md'

env:
    # Secrets required by the Twitter API
    TWITTER_CONSUMER_KEY : ${{ secrets.TWITTER_CONSUMER_KEY }}
    TWITTER_CONSUMER_SECRET : ${{ secrets.TWITTER_CONSUMER_SECRET }}
    TWITTER_ACCESS_TOKEN : ${{ secrets.TWITTER_ACCESS_TOKEN }}
    TWITTER_ACCESS_TOKEN_SECRET : ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

    # Secrets required to connect to the Elastic DB
    ELASTIC_PROTOCOL : ${{ secrets.ELASTIC_PROTOCOL }}
    ELASTIC_ADDRESS : ${{ secrets.ELASTIC_ADDRESS }}
    ELASTIC_PORT : ${{ secrets.ELASTIC_PORT }}
    ELASTIC_USER : ${{ secrets.ELASTIC_USER }}
    ELASTIC_PASS : ${{ secrets.ELASTIC_PASS }}

jobs:
    test_code:
        name: Run pytest
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            
            - name: Set up Python
              uses: actions/setup-python@v1
              with:
                python-version: '3.7'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
                pip install pytest
            
            - name: Run pytest
              run: |
                python -m pytest tests